#!/bin/bash
#SBATCH -n 1
#SBATCH -c 1
#SBATCH --mem=64G
#SBATCH -p qTRD
#SBATCH --time=20:00:00
#SBATCH -J poly
#SBATCH -e /data/users2/jwardell1/undersampling-project/jobs/error%A.err
#SBATCH -o /data/users2/jwardell1/undersampling-project/jobs/out%A.out
#SBATCH -A psy53c17
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwardell1@student.gsu.edu
#SBATCH --oversubscribe


export PATH=/data/users2/jwardell1/miniconda3/bin:$PATH

source /data/users2/jwardell1/miniconda3/etc/profile.d/conda.sh

CONDA_PATH=`which conda`

eval "$(${CONDA_PATH} shell.bash hook)"
conda activate /data/users2/jwardell1/miniconda3/envs/usp

python /data/users2/jwardell1/undersampling-project/OULU/python-scripts/poly_noise1.py



