#!/bin/bash
#SBATCH -n 1
#SBATCH -c 2
#SBATCH --mem=16g
#SBATCH -p qTRD
#SBATCH --time=3-00:00:00
#SBATCH -J LS5-3-O
#SBATCH -e /data/users2/jwardell1/undersampling-project/jobs/error%A_%a.err
#SBATCH -o /data/users2/jwardell1/undersampling-project/jobs/out%A_%a.out
#SBATCH -A psy53c17
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwardell1@student.gsu.edu
#SBATCH --oversubscribe

export TMPDIR=/data/users2/jwardell1/tmp

export PATH=/data/users2/jwardell1/miniconda3/bin:$PATH

source /data/users2/jwardell1/miniconda3/etc/profile.d/conda.sh

CONDA_PATH=`which conda`

eval "$(${CONDA_PATH} shell.bash hook)"
conda activate /data/users2/jwardell1/miniconda3/envs/usp


echo "SLURM_ARRAY_TASK_ID $SLURM_ARRAY_TASK_ID"
echo "hostname $hostname"


#SLURM_ARRAY_TASK_ID=0

python /data/users2/jwardell1/undersampling-project/OULU/python-scripts/SVM/nopoly_libsvm.py
