#!/bin/bash
#SBATCH -n 1
#SBATCH -c 20
#SBATCH --mem=32g
#SBATCH -p qTRD
#SBATCH --time=01:00:00
#SBATCH -J pnoulu
#SBATCH -e /data/users2/jwardell1/undersampling-project/jobs/error%A_%a.err
#SBATCH -o /data/users2/jwardell1/undersampling-project/jobs/out%A_%a.out
#SBATCH -A psy53c17
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwardell1@student.gsu.edu
#SBATCH --oversubscribe


export PATH=/data/users2/jwardell1/miniconda3/bin:$PATH

source /data/users2/jwardell1/miniconda3/etc/profile.d/conda.sh

CONDA_PATH=`which conda`

eval "$(${CONDA_PATH} shell.bash hook)"
conda activate /data/users2/jwardell1/miniconda3/envs/usp


#SLURM_ARRAY_TASK_ID=0

PATHS_FILE=/data/users2/jwardell1/undersampling-project/OULU/txt-files/paths_graphs
paths_array=($(cat ${PATHS_FILE}))

snr_ix=$(( 3*$SLURM_ARRAY_TASK_ID ))
snr=${paths_array[${snr_ix}]}

graph_ix=$(( 3*$SLURM_ARRAY_TASK_ID + 1 ))
graph_filepath=${paths_array[${graph_ix}]}


graph_no=$(( 3*$SLURM_ARRAY_TASK_ID + 2 ))
graph_label=${paths_array[${graph_no}]}


python /data/users2/jwardell1/undersampling-project/OULU/python-scripts/poly_noise1.py $snr $graph_filepath $graph_no
