#!/bin/bash
#SBATCH -n 1
#SBATCH -c 2
#SBATCH --mem=32g
#SBATCH -p qTRD
#SBATCH --time=12:00:00
#SBATCH -J perm
#SBATCH -e /data/users2/jwardell1/undersampling-project/jobs/error%A_%a.err
#SBATCH -o /data/users2/jwardell1/undersampling-project/jobs/out%A_%a.out
#SBATCH -A psy53c17
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwardell1@student.gsu.edu
#SBATCH --oversubscribe


export PATH=/data/users2/jwardell1/miniconda3/bin:$PATH

source /data/users2/jwardell1/miniconda3/etc/profile.d/conda.sh

CONDA_PATH=`which conda`

eval "$(${CONDA_PATH} shell.bash hook)"
conda activate /data/users2/jwardell1/miniconda3/envs/usp_fix

echo "SLURM_ARRAY_TASK_ID $SLURM_ARRAY_TASK_ID"
hostname=`hostname`
echo "hostname $hostname"


python /data/users2/jwardell1/undersampling-project/perm.py
